[package]
name = "efence"
version.workspace = true
authors.workspace = true
description = "Crate of efense holding shared tools, (with_std)"
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
aya = { workspace = true }
chrono = { workspace = true }
efence_core = { path = "../lib_nostd" }
libc = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }

[lib]
path = "lib.rs"
